### Numpy Array Operations 

In [1]:
import numpy as np

### Slicing

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Steps", arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
With Steps [2 4 6 8]
Negative Indexing 8


### Slicing with 2d array

In [3]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


print("Specific element",arr_2d[1,2])
print("Entire Row ", arr_2d[0])
print("Entire Column ",arr_2d[:,1])



Specific element 6
Entire Row  [1 2 3]
Entire Column  [2 5 8]


### Sorting

In [4]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("Sorted Array ",np.sort((unsorted)))
print(unsorted)

# it does not make changes in original array

arr_2d_unsorted=np.array([[3,1],[1,2],[3,2]])

print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by row",np.sort(arr_2d_unsorted,axis=1))

# axis=1 (row)
# axis=0 (column)



Sorted Array  [1 1 2 3 4 5 6 9]
[3 1 4 1 5 9 2 6]
Sorted 2D array by column [[1 1]
 [3 2]
 [3 2]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


### Filter

In [5]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print("Even Numbers",even_numbers)

Even Numbers [ 2  4  6  8 10]


### Filter with mask
#### In NumPy, mask filtering means creating a Boolean condition and using it to select elements.

In [6]:
mask=numbers>5
print(mask)
print("Numbers greater than 5 ",numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [7]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [8]:
condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)
print(numbers)

[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]


### Adding and removing data

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# combined=arr1+arr2 
# will not combine it will add it

combined=np.concatenate((arr1,arr2))
print(combined)

arr3=np.array([1,2,3,4,5])
deleted=np.delete(arr3,2)
print(arr3)
print("Array After deletion " ,deleted)


arr4 = np.array([1, 2, 3])
append_array = np.append(arr4, 4)
print("append array",append_array)
print(arr4)


arr5 = np.array([1, 2, 3])
inserted_array = np.insert(arr5, 1, 10)
print("inserted array",inserted_array)
print(arr5)



[1 2 3 4 5 6]
[1 2 3 4 5]
Array After deletion  [1 2 4 5]
append array [1 2 3 4]
[1 2 3]
inserted array [ 1 10  2  3]
[1 2 3]


### Array Compatibilty

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatibility shapes",a.shape==b.shape)

original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(original)
print(with_new_col)


Compatibility shapes True
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]
