## Numpy Array and basics


In [1]:
import numpy as np 
import time

### create array from list


In [2]:
arr_1=np.array([1,2,3,4,5])
print("1D Array : ", arr_1)


arr_2=np.array([[1,2,3],[4,5,6]])
print("2D Array : ",arr_2)



1D Array :  [1 2 3 4 5]
2D Array :  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [3]:
py_list=[1,2,3,4]
print("Python list mutiplication ", py_list*2)

np_array=np.array([1,2,3])
print("Python array  mutiplication ", np_array*2)

start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List opertion time: ",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("\n Numpy opertion time: ",time.time()-start)


Python list mutiplication  [1, 2, 3, 4, 1, 2, 3, 4]
Python array  mutiplication  [2 4 6]

 List opertion time:  0.11357378959655762

 Numpy opertion time:  0.0010459423065185547


### creating array from scratch


In [4]:
zeros=np.zeros((3,4))
print("zeros array :\n",zeros)

ones=np.ones((2,3))
print("ones array :\n",ones)

full= np.full((2,2),7)
print("constant  array :\n",full)

random=np.random.random((2,3))
print("random array :\n",random)

sequence=np.arange(0,10,2)
print("sequence array :\n",sequence)

zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
constant  array :
 [[7 7]
 [7 7]]
random array :
 [[0.48079699 0.28117884 0.73890139]
 [0.72039375 0.09739021 0.99404683]]
sequence array :
 [0 2 4 6 8]


### Vector,Matrix and Tensor

Scalar → 0D
   
Vector → 1D
   
Matrix → 2D
   
Tensor → 3D or higher

In [5]:
vector=np.array([1,2,3])
print("Vector : ",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix : ",matrix)

tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor : ",tensor)



Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("Shape " ,arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("Dtype ",arr.dtype)

[[1 2 3]
 [4 5 6]]
Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


### Array Reshaping

In [7]:
arr=np.arange(12)
print("Original Array ",arr)

reshaped=arr.reshape((4,3))
print("\nReshaped Array ", reshaped)


flattened=reshaped.flatten()
print("\nFlatten Array ",flattened)

# ravel (return view ,instead of copy)
raveled=reshaped.ravel()
print("\nRaveled ",raveled)
raveled[0] = 100
#flattened[0]=100

print(reshaped)

## Tranpose
transpose =reshaped.T
print("\n Tranpose",transpose)



Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flatten Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]

 Tranpose [[100   3   6   9]
 [  1   4   7  10]
 [  2   5   8  11]]
